### ISSUE TITLE
link time error for standalone examples

### ISSUE THREAD

**Issue by jfdev001** [Cambridge-ICCS/FTorch#435]
# Problem Summary
FTorch can of course be successfully built by itself and examples are successfully executed during the integration test suite; however, when I attempt to run the examples just by themselves (i.e., running them not during testing suite), I encounter the the below error during link time:

```text
/usr/bin/ld: warning: libtorch.so, needed by /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `vtable for torch::autograd::AutogradMeta'
```

# Proposed Solution

Simply adding

```cmake
get_filename_component(TORCH_LIBRARY_DIR ${TORCH_LIBRARY} DIRECTORY)
target_link_options(${LIB_NAME} PRIVATE "LINKER:-rpath,${TORCH_LIBRARY_DIR}")
```

after

https://github.com/Cambridge-ICCS/FTorch/blob/05fab9fa15d94165969b63b60f6d435da0b00ae9/CMakeLists.txt#L128

fixes the issue.

I have a branch https://github.com/jfdev001/FTorch/tree/jfrazier/link-issue-in-example ready to go with this fix that I can use to open a PR here. Just lmk what you think!

# Reproducing Error and Demonstrating Proposed Solution

```bash
#
# @file Dockerfile
# 
# @brief Reproduce Link time error in standalone example using 
#        cmake latest (v4.1.1 as of 2025-09-28)
#        Once starting the container in interactive mode, you can check the
#        error output with 
#        `vi $HOME/FTorch/examples/1_Tensor/build-cmake-4.1.1/err.out`
#
FROM ubuntu:latest 
SHELL ["/bin/bash", "-c"]

# Prevent interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

# --- System dependencies ---
RUN apt-get update && apt-get install -y \
    # some text editors for convenience :)
    vim-tiny \
    nano \ 
    git \
    build-essential \
    cmake \
    gfortran \
    python3 \
    python3-venv \
    python3-pip \
    python3-dev \
    openmpi-bin \
    openmpi-common \
    libopenmpi-dev \
    wget \
    && rm -rf /var/lib/apt/lists/*

# Install cmake latest 
RUN wget https://github.com/Kitware/CMake/releases/download/v4.1.1/cmake-4.1.1-linux-x86_64.tar.gz \
    && tar -xf cmake-4.1.1-linux-x86_64.tar.gz \
    && ln -s /cmake-4.1.1-linux-x86_64/bin/cmake /usr/bin/cmake-4.1.1

# Create non-root user since otherwise mpi_infer* tests fail due to some issue
# with running mpiexec as root 
RUN useradd -m myuser && echo "myuser:password" | chpasswd && usermod -s /bin/bash myuser
USER myuser 
ARG HOME=/home/myuser 
WORKDIR /home/myuser 

# --- Install pFUnit (v4.12.0 pinned like the workflow) ---
RUN git clone -b v4.12.0 https://github.com/Goddard-Fortran-Ecosystem/pFUnit.git \
 && export FC=/usr/bin/gfortran \
 && export MPIF90=/usr/bin/mpif90 \
 && mkdir pFUnit/build \
 && cd pFUnit/build \
 && cmake .. \
 && make -j$(nproc) install

# --- Build FTorch from official repo using cmake latest (4.1.1) --
RUN git clone https://github.com/Cambridge-ICCS/FTorch.git
WORKDIR $HOME/FTorch

# setup venv 
RUN python3 -m venv .venv \
 && . $HOME/FTorch/.venv/bin/activate \
 && pip install --upgrade pip \
 && pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu

# build ftorch 
ARG build_dir=build-cmake-4.1.1
ARG cmake_bin=cmake-4.1.1
RUN . /$HOME/FTorch/.venv/bin/activate \
 && export VN=$(python3 -c "import sys; print('.'.join(sys.version.split('.')[:2]))") \
 && export Torch_DIR=/$HOME/FTorch/.venv/lib/python${VN}/site-packages \
 && export PFUNIT_DIR=/$HOME/pFUnit/build/installed/PFUNIT-4.12 \
 && mkdir $build_dir \
 && cd $build_dir \
 && $cmake_bin .. \
      -DPython_EXECUTABLE="$(which python3)" \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=/$HOME/FTorch/$build_dir \
      -DCMAKE_BUILD_TESTS=TRUE \
      -DCMAKE_PREFIX_PATH="${PFUNIT_DIR};${Torch_DIR}" \
 && $cmake_bin --build . \
 && $cmake_bin --install .

# NOTE: This fails due to linking error at compile time, so go and inspect 
# stderr below
# $HOME/FTorch/examples/1_Tensor/build-cmake-4.1.1/err.out 
RUN cd $HOME/FTorch/examples/1_Tensor \
  && mkdir $build_dir \
  && $cmake_bin -S . -B $build_dir -DCMAKE_PREFIX_PATH=~/FTorch/$build_dir \
  && $cmake_bin --build $build_dir > $build_dir/err.out 2>&1 || true \
  && export error=$(grep Error $build_dir/err.out) \
  && if [[ -z $error ]]; then ./$build_dir/tensor_manipulation; fi;

# -- Build FTorch using my version with the latest version of cmake and my fix-- 
WORKDIR $HOME
RUN git clone --branch jfrazier/link-issue-in-example https://github.com/jfdev001/FTorch.git FTorch-jfrazier
WORKDIR $HOME/FTorch-jfrazier

# NOTE: Redundant pytorch CPU installation...
RUN python3 -m venv .venv \
 && . $HOME/FTorch-jfrazier/.venv/bin/activate \
 && pip install --upgrade pip \
 && pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu

# build new ftorch 
ARG build_dir=build-cmake-4.1.1
ARG cmake_bin=cmake-4.1.1
RUN . /$HOME/FTorch-jfrazier/.venv/bin/activate \
 && export VN=$(python3 -c "import sys; print('.'.join(sys.version.split('.')[:2]))") \
 && export Torch_DIR=/$HOME/FTorch-jfrazier/.venv/lib/python${VN}/site-packages \
 && export PFUNIT_DIR=/$HOME/pFUnit/build/installed/PFUNIT-4.12 \
 && mkdir $build_dir \
 && cd $build_dir \
 && $cmake_bin .. \
      -DPython_EXECUTABLE="$(which python3)" \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=/$HOME/FTorch-jfrazier/$build_dir \
      -DCMAKE_BUILD_TESTS=TRUE \
      -DCMAKE_PREFIX_PATH="${PFUNIT_DIR};${Torch_DIR}" \
 && $cmake_bin --build . \
 && $cmake_bin --install .

# NOTE: Build example binary without an issue 
RUN cd $HOME/FTorch-jfrazier/examples/1_Tensor \
  && mkdir $build_dir \
  && $cmake_bin -S . -B $build_dir -DCMAKE_PREFIX_PATH=~/FTorch-jfrazier/$build_dir \
  && $cmake_bin --build $build_dir > $build_dir/err.out 2>&1 || true \
  && export error=$(grep Error $build_dir/err.out) \
  && if [[ -z $error ]]; then ./$build_dir/tensor_manipulation; fi;

# --- Default command ---
WORKDIR $HOME 
CMD ["/bin/bash"]
```

# Full Error Output 
```text
[ 50%] Building Fortran object CMakeFiles/tensor_manipulation.dir/tensor_manipulation.f90.o
[100%] Linking Fortran executable tensor_manipulation
/usr/bin/ld: warning: libc10.so, needed by /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libtorch_cpu.so, needed by /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libtorch.so, needed by /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `vtable for torch::autograd::AutogradMeta'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `at::TensorBase::retains_grad() const'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `c10::GradMode::is_enabled()'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `vtable for torch::jit::Method'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `c10::detail::torchInternalAssertFail(char const*, char const*, unsigned int, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `c10::TensorImpl::requires_grad() const'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `at::_ops::mul_Tensor::call(at::Tensor const&, at::Tensor const&)'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `c10::impl::ExcludeDispatchKeyGuard::ExcludeDispatchKeyGuard(c10::DispatchKeySet)'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `c10::IValue::reportToTensorTypeError() const'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `at::_ops::div_Tensor::call(at::Tensor const&, at::Tensor const&)'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `at::_ops::sum::call(at::Tensor const&, std::optional<c10::ScalarType>)'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `at::_ops::ones::call(c10::ArrayRef<c10::SymInt>, std::optional<c10::ScalarType>, std::optional<c10::Layout>, std::optional<c10::Device>, std::optional<bool>)'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `at::TensorMaker::make_tensor()'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `at::Tensor::_backward(c10::ArrayRef<at::Tensor>, std::optional<at::Tensor> const&, std::optional<bool>, bool) const'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `at::TensorBase::requires_grad_(bool) const'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `at::_ops::to_dtype_layout::call(at::Tensor const&, std::optional<c10::ScalarType>, std::optional<c10::Layout>, std::optional<c10::Device>, std::optional<bool>, bool, bool, std::optional<c10::MemoryFormat>)'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `typeinfo for c10::Error'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `c10::TensorImpl::set_autograd_meta(std::unique_ptr<c10::AutogradMetaInterface, std::default_delete<c10::AutogradMetaInterface> >)'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `at::_ops::empty_memory_format::call(c10::ArrayRef<c10::SymInt>, std::optional<c10::ScalarType>, std::optional<c10::Layout>, std::optional<c10::Device>, std::optional<bool>, std::optional<c10::MemoryFormat>)'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `c10::ListType::get(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, c10::Type::SingletonOrSharedTypePtr<c10::Type>)'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `caffe2::TypeMeta::typeMetaDatas()'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `c10::warn(c10::Warning const&)'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `c10::GradMode::set_enabled(bool)'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `at::_ops::add_Tensor::call(at::Tensor const&, at::Tensor const&, c10::Scalar const&)'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `at::_ops::zeros::call(c10::ArrayRef<c10::SymInt>, std::optional<c10::ScalarType>, std::optional<c10::Layout>, std::optional<c10::Device>, std::optional<bool>)'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `c10::StringType::get()'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `c10::AnyType::get()'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `at::_ops::zero_::call(at::Tensor&)'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `torch::jit::Object::find_method(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `at::_ops::to_device::call(at::Tensor const&, c10::Device, c10::ScalarType, bool, bool, std::optional<c10::MemoryFormat>)'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `at::_ops::sub_Tensor::call(at::Tensor const&, at::Tensor const&, c10::Scalar const&)'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `torch::jit::Method::operator()(std::vector<c10::IValue, std::allocator<c10::IValue> >, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, c10::IValue, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, c10::IValue> > > const&) const'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `at::print(std::ostream&, at::Tensor const&, long)'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `c10::UndefinedTensorImpl::_singleton'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `c10::impl::ExcludeDispatchKeyGuard::~ExcludeDispatchKeyGuard()'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `at::_ops::mean::call(at::Tensor const&, std::optional<c10::ScalarType>)'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `c10::operator<<(std::ostream&, c10::DeviceType)'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `caffe2::TypeMeta::error_unsupported_typemeta(caffe2::TypeMeta)'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `torch::jit::load(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::optional<c10::Device>, bool)'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `c10::TensorImpl::grad() const'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `at::_ops::pow_Tensor_Scalar::call(at::Tensor const&, c10::Scalar const&)'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `at::TensorBase::is_leaf() const'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `at::_ops::copy_::call(at::Tensor&, at::Tensor const&, bool)'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `torch::jit::Module::train(bool)'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `c10::AutogradMetaInterface::~AutogradMetaInterface()'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `c10::Warning::Warning(std::variant<c10::Warning::UserWarning, c10::Warning::DeprecationWarning>, c10::SourceLocation, char const*, bool)'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `c10::TensorImpl::mutable_grad()'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `c10::detail::torchCheckFail(char const*, char const*, unsigned int, char const*)'
/usr/bin/ld: /home/myuser/FTorch/build-cmake-4.1.1/lib/libftorch.so: undefined reference to `at::_ops::neg::call(at::Tensor const&)'
collect2: error: ld returned 1 exit status
gmake[2]: *** [CMakeFiles/tensor_manipulation.dir/build.make:101: tensor_manipulation] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:87: CMakeFiles/tensor_manipulation.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
```

**Comment by jatkinson1000** [comment]
Hi @jfdev001 that generally seems like something we'd want, so thanks for checking and raising.

Before proceeding it'd be useful to understand why this happens.
Is it related to changes introduced by #434 or is it something new in CMake v4 above v3?
Does the issue also show up if you use CMake v3?

If you could add a brief description of what the additional lines do and how/why they resolve the issue, either here or/and in a PR that would be appreciated.

**Comment by jatkinson1000** [comment]
It's yours @jfdev001 and thanks for the details and looking into this.

Indeed, it was something I thought about last night that we should perhaps have a separate 'standalone examples' CI job.
